name = "VET_A3_Monocraft"
author = "veteran29"
prefix = "vet_monocraft"
mainprefix = "z"

[files]
include = [
    "LICENSE",
    "mod.cpp",
    "README.md",
]

exclude = ["*.psd", "*.png", "*.tga"]

[properties]
author = "veteran29"

[version]
path = "addons/main/script_version.hpp"

[hemtt.launch]
workshop = [
    "2369477168", # ADT
    # "450814997", # CBA_A3
    # "1638341685", # DUI
]
parameters = [
    "-debug",
    "-filePatching",
    "-name=dev",
    "-noSplash",
    "-showScriptErrors",
    "-window",
]
